substitutions:
  device_name: waterlezer
  device_description: Water meter sensor 
  version: "v22.12.2"

esphome:
  name: ${device_name}
  comment: "${device_description}" 
  name_add_mac_suffix: false
  platformio_options:
    upload_speed: 921600
  
  project:
    name: smartstuff.waterlezer
    version: ${version}
  
esp8266:
  board: esp12e
  restore_from_flash: true

status_led:
  pin:
    number: 2
    inverted: true

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      hidden: !secret wifi_hidden
  ap:
    ssid: ${device_name}
  power_save_mode: LIGHT
  fast_connect: true
  manual_ip:
    static_ip: !secret wifi_ip
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
    dns1: !secret wifi_dns

web_server:
  port: 80
  
captive_portal:

logger:
  level: INFO

ota:
  reboot_timeout: 10min
  num_attempts: 5

globals:
  - id: totalWaterUsage
    type: int
    restore_value: true
    initial_value: '0'

number:
  - platform: template
    name: "Set water reading"
    min_value: 0
    max_value: 99999
    step: 1
    icon: mdi:water
    device_class: water
    entity_category: config
    unit_of_measurement: L
    mode: box
    optimistic: true
    disabled_by_default: true
    set_action:
      then:
        - globals.set:
            id: totalWaterUsage
            value: !lambda "return ( x );"

button:
  - platform: restart
    name: "_Restart device"
  - platform: factory_reset
    name: "_Restart with Factory Default Settings"

sensor:
  - platform: pulse_counter
    pin: 
      number: 5
      mode:
        input: true
        pullup: true #v3.5 aanzetten
    id: watermeter_pulse
    name: "Watermeter pulse"
    count_mode:
      rising_edge: DISABLE
      falling_edge: INCREMENT
    state_class: measurement
    update_interval: 1s
    internal_filter: 100us
    accuracy_decimals: 0
    unit_of_measurement: 'L/min'
  
  - platform: template
    name: "Watermeter total"
    state_class: "total_increasing"
    device_class: "water"
    icon: mdi:water
    update_interval: 1s
    unit_of_measurement: L
    accuracy_decimals: 0
    lambda: |-
      if (id(watermeter_pulse).state > 0) id(totalWaterUsage) += 1;
      return id(totalWaterUsage);
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP-adres
      icon: mdi:ip-network
    ssid:
      name: Netwerk
      icon: mdi:access-point-network
    mac_address:
      name: Mac-adres
      icon: mdi:folder-key-network-outline
      
      
  - platform: template
    name: "Config Version"
    icon: "mdi:label-outline"
    update_interval: 6h
    lambda: return {"${version}"};
      
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true

